--[[
DewDropDown.lua
Defines the table listings for the dropdown lists.
]]

--Invoke all libraries
local AL = LibStub("AceLocale-3.0"):GetLocale("AtlasLoot")
local BabbleBoss = AtlasLoot_GetLocaleLibBabble("LibBabble-Boss-3.0")
local BabbleEpoch = AtlasLoot_GetLocaleLibBabble("LibBabble-Epoch-3.0")
local BabbleFaction = AtlasLoot_GetLocaleLibBabble("LibBabble-Faction-3.0")
local BabbleZone = AtlasLoot_GetLocaleLibBabble("LibBabble-Zone-3.0")
local BabbleInventory = AtlasLoot_GetLocaleLibBabble("LibBabble-Inventory-3.0")

--This is a multi-layer table defining the main loot listing.
--Entries have the text to display, loot table or sub table to link to and if the link is to a loot table or sub table
AtlasLoot_DewDropDown = {
	{
		[AL["Classic Instances"]] = {
			{ { BabbleEpoch["Baradin Hold"], "BaradinHold", "Submenu" }, },
			{ { BabbleZone["Blackfathom Deeps"], "BlackfathomDeeps1", "Table" }, },
			{ { BabbleZone["Blackrock Depths"], "BlackrockDepths", "Submenu" }, },
			{ { BabbleZone["Lower Blackrock Spire"], "LowerBlackrock", "Submenu" }, },
			{ { BabbleZone["Upper Blackrock Spire"], "UpperBlackrock", "Submenu" }, },
			{ { BabbleZone["The Deadmines"], "TheDeadmines1", "Table" }, },
			{ { BabbleEpoch["Glittermurk Mines"], "Glittermurk", "Table" }, },
			{ { BabbleZone["Gnomeregan"], "Gnomeregan1", "Table" }, },
			{ { BabbleZone["Maraudon"], "Maraudon1", "Table" }, },
			{ { BabbleZone["Ragefire Chasm"], "RagefireChasm", "Table" }, },
			{ { BabbleZone["Razorfen Downs"], "RazorfenDowns1", "Table" }, },
			{ { BabbleZone["Razorfen Kraul"], "RazorfenKraul1", "Table" }, },
			{ { BabbleZone["Scarlet Monastery"], "Scarlet Monastery", "Submenu" }, },
			{ { BabbleZone["Scholomance"], "Scholomance", "Submenu" }, },
			{ { BabbleZone["Shadowfang Keep"], "ShadowfangKeep1", "Table" }, },
			{ { BabbleZone["The Stockade"], "TheStockade", "Table" }, },
			{ { BabbleEpoch["Stonetalon Caverns"], "StonetalonCaverns", "Table" }, },
			{ { BabbleZone["Stratholme"], "Stratholme", "Submenu" }, },
			{ { BabbleZone["The Temple of Atal'Hakkar"], "SunkenTemple", "Submenu" }, },
			{ { BabbleZone["Uldaman"], "Uldaman", "Submenu" }, },
			{ { BabbleZone["Wailing Caverns"], "WailingCaverns1", "Table" }, },
			{ { BabbleZone["Zul'Farrak"], "ZulFarrak", "Submenu" }, },
		},
	},
	{
		[AL["Raids"]] = {
			{ { BabbleZone["Onyxia's Lair"], "OnyxiasLair", "Submenu" }, },
			{ { BabbleZone["Molten Core"], "MoltenCore", "Submenu" }, },
		},
	},
	{
		{ AL["World Bosses"], "WORLDBOSSMENU", "Table" }
		-- [AL["World Bosses"]] = {
		-- 	{ { BabbleEpoch["Corrupted Ancient"], "Corruptedancient", "Table" }, },
		-- 	{ { BabbleEpoch["Gonzor"], "Gonzor", "Table" }, },
		-- 	{ { BabbleEpoch["King Gnok"], "Kinggnok", "Table" }, },
		-- 	{ { BabbleEpoch["King Mosh"], "KingMosh", "Table" }, },
		-- 	{ { BabbleEpoch["Silithid Lurker"], "Silithidlurker", "Table" }, },
		-- 	{ { BabbleEpoch["Volchan"], "Volchan", "Table" }, },
		-- 	{ { BabbleEpoch["Lord Kazzak"], "LordKazzak", "Table" }, },
		-- },
	},
	{
		{ AL["Crafting"], "CRAFTINGMENU", "Table" },
	},
	{
		{ AL["Sets/Collections"], "SETMENU", "Table" },
	},
	{
		{ AL["PvP Rewards"], "PVPMENU", "Table" },
	},
	{
		{ AL["Reputation Factions"], "REPMENU", "Table" },
	},
	{
		{ AL["World Events"], "WORLDEVENTMENU", "Table" },
	},
}

--This table defines all the subtables needed for the full menu
--Each sub table entry contains the text entry and the loot table that goes wih it
AtlasLoot_DewDropDown_SubTables = {
	["BaradinHold"] = {
		{ "", "BHMorrumus" },
		{ "", "BHHelnurath" },
		{ "", "BHDakmal" },
		{ "", "BHMillhouseManastorm" },
		{ "", "BHIsalien" },
		{ "", "BHGlagut" },
		{ "", "BHAstilosTheHollow" },
		{ "", "BHNazrasash" },
		{ "", "BHCalypso" },
		{ "", "BHPirateLordBlackstone" },
		{ "", "BHRares" },
		{ "", "Epochset" },
	},
	["BlackrockDepths"] = {
		{ "", "BRDLordRoccor" },
		{ "", "BRDHighInterrogatorGerstahn" },
		{ "", "BRDArena" },
		{ "", "VWOWSets44" },
		{ "", "BRDTheldren" },
		{ "", "BRDHoundmaster" },
		{ "", "BRDPyromantLoregrain" },
		{ "", "BRDTheVault" },
		{ "", "BRDWarderStilgiss" },
		{ "", "BRDVerek" },
		{ "", "BRDDoomgrip" },
		{ "", "BRDFineousDarkvire" },
		{ "", "BRDLordIncendius" },
		{ "", "BRDBaelGar" },
		{ "", "BRDGeneralAngerforge" },
		{ "", "BRDGolemLordArgelmach" },
		{ "", "BRDGuzzler" },
		{ "", "BRDGuzzler2" },
		{ "", "BRDFlamelash" },
		{ "", "BRDPanzor" },
		{ "", "BRDTomb" },
		{ "", "BRDMagmus" },
		{ "", "BRDImperatorDagranThaurissan" },
		{ "", "BRDPrincess" },
		{ "", "BRDBSPlans" },
		{ "", "BRDTrash" },
	},
	["LowerBlackrock"] = {
		{ "", "LBRSSpirestoneButcher" },
		{ "", "LBRSOmokk" },
		{ "", "LBRSSpirestoneLord" },
		{ "", "LBRSLordMagus" },
		{ "", "LBRSVosh" },
		{ "", "LBRSVoone" },
		{ "", "LBRSGrayhoof" },
		{ "", "LBRSGrimaxe" },
		{ "", "LBRSSmolderweb" },
		{ "", "LBRSCrystalFang" },
		{ "", "LBRSDoomhowl" },
		{ "", "LBRSZigris" },
		{ "", "LBRSHalycon" },
		{ "", "LBRSSlavener" },
		{ "", "LBRSBashguud" },
		{ "", "LBRSWyrmthalak" },
		{ "", "LBRSFelguard" },
		{ "", "LBRSTrash" },
		{ "", "VWOWWeapons1" },
	},
	["OnyxiasLair"] = {
		{ "", "OnyxiaOrtorg" },
		{ "", "OnyxiaAtressian" },
		{ "", "OnyxiaBoss" },
		{ "", "OnyxiaTrash" },
	},
	["MoltenCore"] = {
		{ "", "MCLucifron" },
		{ "", "MCMagmadar" },
		{ "", "MCGehennas" },
		{ "", "MCGarr" },
		{ "", "MCShazzrah" },
		{ "", "MCGeddon" },
		{ "", "MCGolemagg" },
		{ "", "MCSulfuron" },
		{ "", "MCMajordomo" },
		{ "", "MCRagnaros" },
		{ "", "MCRANDOMBOSSDROPPS" },
		{ "", "MCTrashMobs" },
	},
	["UpperBlackrock"] = {
		{ "", "UBRSEmberseer" },
		{ "", "UBRSSolakar" },
		{ "", "UBRSRunewatcher" },
		{ "", "UBRSAnvilcrack" },
		{ "", "UBRSRend" },
		{ "", "UBRSBeast" },
		{ "", "UBRSValthalak" },
		{ "", "UBRSDrakkisath" },
		{ "", "UBRSTrash" },
		{ "", "VWOWWeapons2" },
	},
	["Scarlet Monastery"] = {
		{ BabbleZone["Armory"], "SMHerod" },
		{ "", "SMCathedral" },
		{ "", "SMGraveyard" },
		{ "", "SMLibrary" },
		{ "", "SMTrash" },
		{ AL["Set: Chain of the Scarlet Crusade"], "VWOWSets33" },
	},
	["Scholomance"] = {
		{ "", "SCHOLOKirtonostheHerald" },
		{ "", "SCHOLOJandiceBarov" },
		{ "", "SCHOLORattlegore" },
		{ "", "SCHOLODeathKnight" },
		{ "", "SCHOLOMarduk" },
		{ "", "SCHOLOVectus" },
		{ "", "SCHOLORasFrostwhisper" },
		{ "", "SCHOLOKormok" },
		{ "", "SCHOLOInstructorMalicia" },
		{ "", "SCHOLODoctorTheolenKrastinov" },
		{ "", "SCHOLOLorekeeperPolkelt" },
		{ "", "SCHOLOTheRavenian" },
		{ "", "SCHOLOLordAlexeiBarov" },
		{ "", "SCHOLOLadyIlluciaBarov" },
		{ "", "SCHOLOBasement" },
		{ "", "SCHOLODarkmasterGandling" },
		{ "", "SCHOLOTrash" },
		{ BabbleEpoch["Scholomance Sets"], "VWOWScholol1" },
	},
	["Stratholme"] = {
		{ BabbleBoss["Skul"], "STRATSkull" },
		{ AtlasLoot_TableNames["STRATStratholmeCourier"][1], "STRATStratholmeCourier" },
		{ BabbleBoss["Fras Siabi"], "STRATFrasSiabi" },
		{ BabbleBoss["Hearthsinger Forresten"], "STRATHearthsingerForresten" },
		{ BabbleBoss["The Unforgiven"], "STRATTheUnforgiven" },
		{ BabbleBoss["Timmy the Cruel"], "STRATTimmytheCruel" },
		{ AtlasLoot_TableNames["STRATMalorsStrongbox"][1], "STRATMalorsStrongbox" },
		{ BabbleBoss["Crimson Hammersmith"], "STRATCrimsonHammersmith" },
		{ AtlasLoot_TableNames["STRATBSPlansSerenity"][1], "STRATBSPlansSerenity" },
		{ BabbleBoss["Cannon Master Willey"], "STRATCannonMasterWilley" },
		{ BabbleBoss["Archivist Galford"], "STRATArchivistGalford" },
		{ BabbleBoss["Balnazzar"], "STRATBalnazzar" },
		{ AL["Sothos and Jarien"], "STRATSothosJarien" },
		{ AtlasLoot_TableNames["STRATStonespine"][1], "STRATStonespine" },
		{ BabbleBoss["Baroness Anastari"], "STRATBaronessAnastari" },
		{ BabbleBoss["Black Guard Swordsmith"], "STRATBlackGuardSwordsmith" },
		{ AtlasLoot_TableNames["STRATBSPlansCorruption"][1], "STRATBSPlansCorruption" },
		{ BabbleBoss["Nerub'enkan"], "STRATNerubenkan" },
		{ BabbleBoss["Maleki the Pallid"], "STRATMalekithePallid" },
		{ BabbleBoss["Magistrate Barthilas"], "STRATMagistrateBarthilas" },
		{ BabbleBoss["Ramstein the Gorger"], "STRATRamsteintheGorger" },
		{ BabbleBoss["Baron Rivendare"], "STRATBaronRivendare" },
		{ AL["Trash Mobs"], "STRATTrash" },
		{ AL["Set: The Postmaster"], "VWOWSets55" },
	},
	["SunkenTemple"] = {
		{ AtlasLoot_TableNames["STSpawnOfHakkar"][1], "STSpawnOfHakkar" },
		{ AtlasLoot_TableNames["STTrollMinibosses"][1], "STTrollMinibosses" },
		{ BabbleBoss["Atal'alarion"], "STAtalalarion" },
		{ BabbleBoss["Dreamscythe"], "STDreamscythe" },
		{ BabbleBoss["Weaver"], "STWeaver" },
		{ BabbleBoss["Avatar of Hakkar"], "STAvatarofHakkar" },
		{ BabbleBoss["Jammal'an the Prophet"], "STJammalan" },
		{ BabbleBoss["Ogom the Wretched"], "STOgom" },
		{ BabbleBoss["Morphaz"], "STMorphaz" },
		{ BabbleBoss["Hazzas"], "STHazzas" },
		{ BabbleBoss["Shade of Eranikus"], "STEranikus" },
		{ AL["Trash Mobs"], "STTrash" },
	},
	["Uldaman"] = {
		{ AtlasLoot_TableNames["UldBaelog"][1], "UldBaelog" },
		{ BabbleBoss["Revelosh"], "UldRevelosh" },
		{ BabbleBoss["Ironaya"], "UldIronaya" },
		{ BabbleBoss["Obsidian Sentinel"], "UldObsidianSentinel" },
		{ BabbleBoss["Ancient Stone Keeper"], "UldAncientStoneKeeper" },
		{ BabbleBoss["Galgann Firehammer"], "UldGalgannFirehammer" },
		{ BabbleBoss["Grimlok"], "UldGrimlok" },
		{ BabbleBoss["Archaedas"], "UldArchaedas" },
		{ BabbleEpoch["Uldic Set"], "VWOWSets77" },
		{ AL["Trash Mobs"], "UldTrash" },
	},
	["ZulFarrak"] = {
		{ BabbleBoss["Antu'sul"], "ZFAntusul" },
		{ BabbleBoss["Theka the Martyr"], "ZFThekatheMartyr" },
		{ BabbleBoss["Witch Doctor Zum'rah"], "ZFWitchDoctorZumrah" },
		{ BabbleBoss["Nekrum Gutchewer"], "ZFNekrumGutchewer" },
		{ BabbleBoss["Shadowpriest Sezz'ziz"], "ZFSezzziz" },
		{ BabbleBoss["Dustwraith"], "ZFDustwraith" },
		{ BabbleBoss["Sandfury Executioner"], "ZFSandfury" },
		{ BabbleBoss["Sergeant Bly"], "ZFSergeantBly" },
		{ BabbleBoss["Hydromancer Velratha"], "ZFHydromancerVelratha" },
		{ BabbleBoss["Gahz'rilla"], "ZFGahzrilla" },
		{ BabbleBoss["Chief Ukorz Sandscalp"], "ZFChiefUkorzSandscalp" },
		{ BabbleBoss["Zerillis"], "ZFZerillis" },
		{ AL["Trash Mobs"], "ZFTrash" },
	},
}
